spring.application.name=Medicore
server.port=5000
spring.h2.console.enabled=true
spring.profiles.active=dev
server.tomcat.connection-timeout=600s
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1024MB
spring.servlet.multipart.max-request-size=1024MB
spring.jpa.hibernate.ddl-auto=update

public.urls=/user/login,/user/v1/signup,/user/v1/verifyOtp,/h2-console,/user/v1/forgotPassword
security.secret=medicoreSecret
access.token.expiry.in.hour=1
